### ISSUE TITLE
Some lights not working

### ISSUE THREAD

**Issue by nakulbende** [adafruit/Adalight#14]
Hello, 

I made this wonderful creation, and got really excited even with half of my lights not working. I tried to trouble shoot my issues, but failed to do so - please let me know if this is a known issue or am  I doing something wrong. 

Here is my setup. I have 50 lights in total: 17 on horizontal and 10 on vertical axes. I do not have any gaps as mentioned in the original code. I start on the bottom left corner, wrap it around along the bottom right edge towards right side, and take it from there. 

![img_20170918_211936](https://user-images.githubusercontent.com/8712050/30593243-ec1e14d4-9d17-11e7-9a55-4991edca7b8f.jpg)

My issue is that ONLY my left and top edge pixels are actually working with adalight. I thought there is something wrong with my pixels, but that is not the case (checked by colorswirl and addressing each pixels manually). Even on left and top - there are some corner LEDS that DO NOT work (see fig, I assume the gray is not even processed). I highlight the LEDs that DO seem to work in this figure.

I changed the line for screen as {0,17,10} and addressed coordinates as shown in the figure. Am I missing something?? Also - I am using processing 2.2.1 if that helps. 

Thanks a lot for any help - again this code is just amazing!! and I am so excited to get this working. 

![capture](https://user-images.githubusercontent.com/8712050/30573918-946eb066-9cc4-11e7-801e-05c973287824.PNG)

**Comment by PaintYourDragon** [comment]
Please use forums.adafruit.com for support questions, and copy-and-paste your exact displays[] and leds[] arrays into a 'code' block so we can try them out.

**Comment by nakulbende** [comment]
Here you go

Thanks!

https://forums.adafruit.com/viewtopic.php?f=8&t=123818&p=617995&hilit=adalight#p617995

*Nakul Prabhakar Bende*
*Corporate R&D, PolyOne*
*http://nakulbende.com* <http://nakulbende.com>

*- Ever tried. Ever failed. Try Again. Fail again. Fail better.*
* --Samuel Beckett*

On Tue, Sep 19, 2017 at 6:18 PM, Paint Your Dragon <notifications@github.com
